name: Build Minecraft Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Ensure package-lock.json exists
      run: |
        if (!(Test-Path -Path "package-lock.json")) {
          Write-Host "package-lock.json not found, creating..."
          npm install
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package-lock.json
          git commit -m "chore: Add missing package-lock.json" || exit 0
        } else {
          Write-Host "package-lock.json found, continuing..."
        }
      shell: pwsh

    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: launcher-windows
        path: dist/
        retention-days: 5
