name: Build Minecraft Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Check for package-lock.json
      run: |
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json not found, creating..."
          npm install
          git add package-lock.json
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "chore: Add missing package-lock.json" || true
        else
          echo "package-lock.json found, continuing..."
        fi

    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: launcher-${{ matrix.os }}
        path: dist/
        retention-days: 5
        
